In [52]:
import numpy as np

In [53]:
np.array([1,3])

array([1, 3])

In [54]:
list = [1,3,5,7,9]
arr = np.array(list)
print(np.array(list,ndmin=1))

[1 3 5 7 9]


In [55]:
print(np.array([[1,3],[4,6],[2,5]],ndmin=2))

[[1 3]
 [4 6]
 [2 5]]


In [56]:
arr = np.arange(0,20,1).reshape(5,4)
print(arr)
arr = np.arange(0,20,1).reshape(4,5)
print(arr)
arr = np.arange(0,20,1).reshape(10,2)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


## Size and Shape

In [57]:
arr = np.array([[5,7,11],[2,5,10],[9,5,8],[9,22,11]])
print(arr)
print("Total:",np.size(arr))
print("Rows:",np.size(arr,0))
print("Cols:",np.size(arr,1))
print("Shape of Array:",arr.shape)

[[ 5  7 11]
 [ 2  5 10]
 [ 9  5  8]
 [ 9 22 11]]
Total: 12
Rows: 4
Cols: 3
Shape of Array: (4, 3)


## Dtype and ndim Function

In [58]:
print('Array:',arr)
print('datatype:',arr.dtype)
print('dimensions:',arr.ndim)

Array: [[ 5  7 11]
 [ 2  5 10]
 [ 9  5  8]
 [ 9 22 11]]
datatype: int32
dimensions: 2


## Array Generation Functions

In [59]:
print(np.arange(1,6),'\n')
print(np.zeros(shape=(4,3),dtype='float64'),'\n')
print(np.ones(shape=(5,5),dtype='int32'),'\n')
print(np.eye(5,dtype='int64'))
print(np.empty(shape = (5,5)))

[1 2 3 4 5] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]] 

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[5.e-324 0.e+000 0.e+000 0.e+000 0.e+000]
 [0.e+000 5.e-324 0.e+000 0.e+000 0.e+000]
 [0.e+000 0.e+000 5.e-324 0.e+000 0.e+000]
 [0.e+000 0.e+000 0.e+000 5.e-324 0.e+000]
 [0.e+000 0.e+000 0.e+000 0.e+000 5.e-324]]


## Random

In [60]:
print(np.random.rand(5,5))

[[0.61691572 0.57113563 0.70995671 0.32146471 0.41559921]
 [0.57109875 0.17900045 0.69925247 0.44983892 0.41243106]
 [0.96673022 0.05400698 0.7224422  0.62802548 0.40858984]
 [0.16459955 0.36382556 0.2570426  0.60734374 0.95602316]
 [0.88243414 0.6255084  0.67046611 0.89716085 0.68176674]]


In [61]:
print(np.random.randint(low=1,high=20,size=12))
arr = np.random.randint(low=1,high=4,size=6)
arr.reshape(3,2)

[17 19  3  7 19  1  2  6  6 14 15 16]


array([[2, 3],
       [3, 3],
       [3, 2]])

In [62]:
print(np.random.randint(low=11,high=51,size=(3,5)))

[[44 35 24 32 35]
 [18 44 31 40 17]
 [30 40 24 33 26]]


## Linshape

The numpy.linspace() function returns number spaces evenly w.r.t interval. Similar to numpy.arange() function but instead of step it uses sample number.
np.linspace(start,stop,restep,number_of_elements,dtype)

In [63]:
np.linspace(1,18,5)

array([ 1.  ,  5.25,  9.5 , 13.75, 18.  ])

## Flatten

In [64]:
arr = np.random.randint(1,9,(5,5))
print(arr)
print(arr.flatten())

[[1 8 4 1 7]
 [2 6 3 5 5]
 [1 8 1 4 1]
 [3 7 6 7 5]
 [7 1 4 1 1]]
[1 8 4 1 7 2 6 3 5 5 1 8 1 4 1 3 7 6 7 5 7 1 4 1 1]


## Logspace

In [65]:
print(np.logspace(2,4,6,base=10))

[  100.           251.18864315   630.95734448  1584.89319246
  3981.07170553 10000.        ]


## Copy Function
when we do a = b , both have the same id. But when we use copy function , both have different i.d so that if we change one , the other wont be affected

In [66]:
arr1 = np.random.randint(1,15,10)

arr2 = arr1

print(arr1, id(arr1))
print(arr2, id(arr2))

print('-'*50)

arr1 = np.random.randint(1,15,10)
arr2 = np.copy(arr1)

print(arr1, id(arr1))
print(arr2, id(arr2))

[ 4  9 13  2  6 12  3  9  4  4] 1774963445808
[ 4  9 13  2  6 12  3  9  4  4] 1774963445808
--------------------------------------------------
[ 6  3  7 10  3 12  2 13 13  5] 1774963446288
[ 6  3  7 10  3 12  2 13 13  5] 1774974897104


## Array Functions

In [67]:
arr = np.random.randint(1,25,(4,3))
arr

array([[19,  1, 16],
       [12,  9, 20],
       [ 2, 19,  3],
       [12,  2,  6]])

In [68]:
print('Max in array:',arr.max())
print('Min in array' ,arr.min())
print('Sum of all numbers in array' , arr.sum())

Max in array: 20
Min in array 1
Sum of all numbers in array 121


In [69]:
print('Col-wise')
print('Max in array:',arr.max(axis=1))
print('Min in array' ,arr.min(axis=1))
print('Sum of all numbers in array' , arr.sum(axis=1))

Col-wise
Max in array: [19 20 19 12]
Min in array [1 9 2 2]
Sum of all numbers in array [36 41 24 20]


In [70]:
print('Row-wise')
print('Max in array:',arr.max(axis=0))
print('Min in array' ,arr.min(axis=0))
print('Sum of all numbers in array' , arr.sum(axis=0))

Row-wise
Max in array: [19 19 20]
Min in array [2 1 3]
Sum of all numbers in array [45 31 45]


## Seed Function:
random() function is used to generate random numbers in Python. Not actually random, rather this is used to generate pseudo-random numbers. That implies that these randomly generated numbers can be determined. random() function generates numbers for some values. This value is also called seed value.

In [71]:
arr = np.random.randint(1,10,(4,3))
print(arr)
print('-'*52)


[[9 4 5]
 [4 5 7]
 [3 7 5]
 [5 2 8]]
----------------------------------------------------


In [72]:
np.random.seed(3)
arr2 = np.random.randint(1,10,(4,3))
print(arr2)

[[9 4 9]
 [9 1 6]
 [4 6 8]
 [7 1 5]]


## Sorting Function

In [73]:
arr = np.random.randint(1,10,(4,4))
print(arr)
print('*'*50)
print('Row-wise:\n',np.sort(arr, axis = 1))
print('-'*15)
print('Col-wise:\n',np.sort(arr, axis = 0,kind='mergesort'))
print('-'*15)


[[8 9 2 7]
 [3 3 2 4]
 [6 9 2 9]
 [8 9 2 1]]
**************************************************
Row-wise:
 [[2 7 8 9]
 [2 3 3 4]
 [2 6 9 9]
 [1 2 8 9]]
---------------
Col-wise:
 [[3 3 2 1]
 [6 9 2 4]
 [8 9 2 7]
 [8 9 2 9]]
---------------


In [74]:
arr = np.random.randint(1,10,(4,4))
print(arr)
arr = np.reshape(np.sort(arr.flatten()),arr.shape)
print(arr)

[[6 5 2 6]
 [5 8 7 1]
 [1 3 5 6]
 [9 9 8 6]]
[[1 1 2 3]
 [5 5 5 6]
 [6 6 6 7]
 [8 8 9 9]]


# Mathematical Operators 

In [75]:
arr = np.random.randint(1,10,(4,3))
print(arr)

[[2 2 2]
 [6 6 8]
 [5 4 1]
 [1 1 1]]


### a.Addition

In [76]:
# Addition
print(arr + 1)
print('-'*20)
#----------------
print(arr + np.random.randint(1,10,(4,3)))

[[3 3 3]
 [7 7 9]
 [6 5 2]
 [2 2 2]]
--------------------
[[ 5  5 10]
 [ 7 12  9]
 [ 7  9  3]
 [ 4  4  6]]


### b.Subtraction

In [77]:
print(arr - 1)
print('-'*20)
#----------------
print(arr - np.random.randint(1,10,(4,3)))

[[1 1 1]
 [5 5 7]
 [4 3 0]
 [0 0 0]]
--------------------
[[-7  1 -5]
 [ 5  1  6]
 [-1  2 -8]
 [-8 -7  0]]


### c. Multiplication

In [78]:
print(arr * 3)
arr2 = np.random.randint(1,10,(4,3))
print(arr*arr2) # in this , we multiply individual elements of matrix

[[ 6  6  6]
 [18 18 24]
 [15 12  3]
 [ 3  3  3]]
[[ 2  4 16]
 [54 48 40]
 [ 5  4  5]
 [ 4  1  9]]


### d. Matrix Multiplication

In [79]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,4],[1,6]])
print(a.dot(b))
print(a@b)

[[ 4 16]
 [10 36]]
[[ 4 16]
 [10 36]]


### e. Division

In [80]:
print(arr / 2)

[[1.  1.  1. ]
 [3.  3.  4. ]
 [2.5 2.  0.5]
 [0.5 0.5 0.5]]


###  f. Power

In [81]:
print(arr ** 2)
print(arr ** 0)

[[ 4  4  4]
 [36 36 64]
 [25 16  1]
 [ 1  1  1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


# Statistical Functions

In [82]:
arr = np.random.randint(1,10,20)
print(arr)

[3 8 3 2 4 3 5 2 3 3 8 4 5 2 7 8 2 1 1 6]


### a)Percentile Function

In [83]:
print(np.percentile(arr,75))

5.25


### b) Mean

In [84]:
print(arr.mean())

4.0


### c) Standard Deviation and Variance

In [85]:
print(arr.var())
print(arr.std())
print(arr.std() ** 2)

5.1
2.258317958127243
5.099999999999999


## Filtering Array

In [86]:
arr = np.random.randint(0,15,20)
print(arr)
print(arr[arr<7])

[11  8  4  8  8 14 12  3  4  9 10  2 12  5  4  7  9 10  1  9]
[4 3 4 2 5 4 1]


## Transpose of Array

In [87]:
arr = np.random.randint(1,20,(3,5))

print(arr)
print('-'*20)
print(arr.T)

[[ 1 14 13  8  5]
 [11  9 13 18  1]
 [ 8  1  2 16 12]]
--------------------
[[ 1 11  8]
 [14  9  1]
 [13 13  2]
 [ 8 18 16]
 [ 5  1 12]]


## Where function

In [88]:
arr = np.random.randint(1,100,10)
print(arr)
print(np.where(arr%2 == 0,'Even',arr))

[18 52 72 14 96 69 95 64 42 14]
['Even' 'Even' 'Even' 'Even' 'Even' '69' '95' 'Even' 'Even' 'Even']


## Merging Arrays

In [89]:
arr1 = np.random.randint(1,10,(2,4))
arr2 = np.random.randint(1,10,(2,4))
print(arr1)
print('-'*15)
print(arr2)

print('-'*30)
print(np.concatenate((arr1,arr2), axis = 0))
print('-'*30)
print(np.concatenate((arr1,arr2), axis = 1))

[[1 9 5 8]
 [9 6 7 8]]
---------------
[[4 6 2 9]
 [3 9 5 6]]
------------------------------
[[1 9 5 8]
 [9 6 7 8]
 [4 6 2 9]
 [3 9 5 6]]
------------------------------
[[1 9 5 8 4 6 2 9]
 [9 6 7 8 3 9 5 6]]


In [90]:
print(np.hstack((arr1,arr2)))
print('-'*20)
print(np.vstack((arr1,arr2)))

[[1 9 5 8 4 6 2 9]
 [9 6 7 8 3 9 5 6]]
--------------------
[[1 9 5 8]
 [9 6 7 8]
 [4 6 2 9]
 [3 9 5 6]]


## Splitting Arrays

In [91]:
arr = np.random.randint(1,10,(4,4))
print(arr)
print(np.vsplit(arr,2),sep = '\n')
print('-' * 20)
print(np.hsplit(arr,4))

[[1 9 8 2]
 [3 6 3 8]
 [7 8 2 6]
 [8 6 8 3]]
[array([[1, 9, 8, 2],
       [3, 6, 3, 8]]), array([[7, 8, 2, 6],
       [8, 6, 8, 3]])]
--------------------
[array([[1],
       [3],
       [7],
       [8]]), array([[9],
       [6],
       [8],
       [6]]), array([[8],
       [3],
       [2],
       [8]]), array([[2],
       [8],
       [6],
       [3]])]
